
/*FETCH ALL DATA FROM TABLE BANK LOAN ANALYSIS*/
SELECT * FROM BANK_LOAN_DATA;

/*FIND TOTAL LOAN APPLICATION*/
SELECT 
	COUNT(ID)AS TOTAL_LOAN_APPLICATION 
FROM BANK_LOAN_DATA;

/*FIND MTD LOAN APPLICATIONS*/
SELECT
	COUNT(ID) AS MTD_LOAN_APPLICATION	
FROM BANK_LOAN_DATA
WHERE MONTH(Issue_Date)='12'

/*FIND PMTD LOAN APPLICATIONS */
SELECT
	COUNT(ID)AS PMTD_LOAN_APPLICATION 
FROM BANK_LOAN_DATA
WHERE MONTH(issue_date)='11';

/*FIND TOTAL FUNDED AMOUNT*/
SELECT
	SUM(loan_amount) AS TOTAL_FUNDED_AMOUNT
FROM BANK_LOAN_DATA;

/*FIND TOTAL FUNDED AMOUNT FOR MONTH 12 OF YEAR 2021 MTD*/
SELECT 
	SUM(loan_amount)AS 'TOTAL FUNDE DAMOUNT' 
FROM BANK_LOAN_DATA
WHERE MONTH(issue_date)='12'AND YEAR(issue_date)=2021;

/*FIND TOTAL FUNDED AMOUNT FOR MONTH 11 F YEAR 2021 PMTD*/
SELECT
	SUM(loan_amount)AS 'TOTAL FUNDED AMOUNT'
FROM BANK_LOAN_DATA
WHERE MONTH(issue_date)='11'AND YEAR(issue_date)=2021;

/*FIND TOTAL AMOUNT RECEIVED*/
SELECT 
	SUM(total_payment)AS 'AMOUNT RECEIVED' 
FROM BANK_LOAN_DATA;

/*FIND MTD TOTAL AMOUNT RECEIVED*/
SELECT 
	SUM(total_payment)AS 'MTD AMOUNT RECEIVED'
FROM BANK_LOAN_DATA
WHERE MONTH(issue_date)='12'AND YEAR(issue_date)=2021;

/*FIND PMTD AMOUNT RECEIVED*/
SELECT 
	SUM(total_payment)AS 'PMTD AMOUNT RECEIVED' 
FROM BANK_LOAN_DATA
WHERE MONTH(issue_date)='11'AND YEAR(issue_date)=2021;

/*FIND AVERAGE INTEREST RATE*/
SELECT 
	CAST(AVG(int_rate)*100 AS DECIMAL(10,2))AS 'AVG INTEREST RATE' 
FROM BANK_LOAN_DATA;

SELECT 
	ROUND(AVG(int_rate),4)*100 AS 'AVG INTEREST RATE' 
FROM BANK_LOAN_DATA;

/*FIND MTD AVERAGE INTEREST RATE*/
SELECT 
	AVG(int_rate)*100 AS 'MTD AVG INTEREST RATE' 
FROM BANK_LOAN_DATA 
WHERE MONTH(issue_date)='12'AND YEAR(issue_date)=2021;

/*FIND PMTD AVERAGE INTEREST RATE*/
SELECT 
	AVG(int_rate)*100 AS 'PMTD AVG INTEREST RATE' 
FROM BANK_LOAN_DATA 
WHERE MONTH(issue_date)='11' AND YEAR(issue_date)=2021;

/* FIND AVERAGE DTI (DEBT-TO-INCOME)*/
SELECT 
	CAST(AVG(dti)*100 AS DECIMAL(10,2))AS 'AVG DTI' 
FROM BANK_LOAN_DATA;

SELECT 
	ROUND(AVG(dti),4)*100 AS 'AVG DTI' 
FROM BANK_LOAN_DATA;

/* FIND mtd AVERAGE DTI (DEBT-TO-INCOME)*/
SELECT 
	CAST(AVG(dti)*100AS DECIMAL(10,2))AS 'AVG DTI' 
FROM BANK_LOAN_DATA
WHERE MONTH(issue_date)='12';

/* FIND PMTD AVERAGE DTI (DEBT-TO-INCOME)*/
SELECT 
	CAST(AVG(dti)*100AS DECIMAL(10,2))AS 'AVG DTI' 
FROM BANK_LOAN_DATA
WHERE MONTH(issue_date)='11';

/*FIND NUMBER OF GOOD LOAN APPLICATIONS*/
SELECT 
	COUNT(ID)AS 'GOOD LOAN APPLICATIONS' 
FROM BANK_LOAN_DATA 
WHERE loan_status IN('FULLY PAID','CURRENT');

/*FIND GOOD LOAN FUNDED AMOUNT*/
SELECT 
	SUM(loan_amount)AS 'FUNDED AMOUNT' 
FROM BANK_LOAN_DATA 
WHERE loan_status IN('CURRENT','FULLY PAID');

/*FIND GOOD LOAN AMOUNT RECEIVED*/
SELECT 
	SUM(total_payment)AS 'AMOUNT RECEIVED' 
FROM BANK_LOAN_DATA 
WHERE loan_status IN('CURRENT','FULLY PAID');

/*FIND GOOD LOAN PERCENTAGE*/
SELECT 
	(COUNT(CASE WHEN loan_status IN('FULLY PAID','CURRENT')THEN ID END)*100)
	/
	COUNT(ID)AS GOOD_LOAN_PERCENTAGE 
FROM BANK_LOAN_DATA

/*FIND BAD LOAN APPLICATIONS*/
SELECT 
	COUNT(ID) AS 'BAD LOAN APPLICATION' 
FROM BANK_LOAN_DATA 
WHERE loan_status='CHARGED OFF';

/*BAD LOAN FUNDED AMOUNT*/
SELECT 
	SUM(loan_amount)AS 'BAD LOAN FUNDED AMOUNT' 
FROM BANK_LOAN_DATA 
WHERE loan_status='CHARGED OFF';

/*BAD LOAN AMOUNT RECEIVED*/
SELECT 
	SUM(total_payment)AS 'BAD LOAN AMOUNT RECEIVED' 
FROM BANK_LOAN_DATA 
WHERE loan_status='CHARGED OFF';

/*FIND BAD LOAN PERCENTAGE*/
SELECT 
	(COUNT(CASE WHEN loan_status='CHARGED OFF' THEN ID END)*100.0)
	/ 
	COUNT(ID) AS 'BAD LOAN PERCENTAGE' 
FROM BANK_LOAN_DATA;

/*LOAN STATUS GRID VIEW*/
SELECT 
	loan_status,
	COUNT(ID) AS 'TOTAL LOAN APPLICATIONS',
	SUM(total_payment)AS 'TOTAL AMOUNT RECEIVED',
	SUM(loan_amount) AS 'TOTAL FUNDED AMOUNT',
	AVG(int_rate * 100) AS 'AVG INTEREST RATE',
	AVG(DTI *100) AS 'AVG DTI'
FROM BANK_LOAN_DATA
GROUP BY loan_status;

/*MTD FUNDED AMOUNT AND MTD RECEIVED AMOUNT ACCORDING TO LOAN STATUS*/
SELECT 
	loan_status,
	SUM(loan_amount) AS 'MTD FUMDED AMOUNT',
	SUM(total_payment) AS 'MTD RECEIVED AMOUNT'
FROM BANK_LOAN_DATA
WHERE MONTH(issue_date)='12'
GROUP BY loan_status;

/*MONTHLY TRENDA BY ISSUE DATE (TOTAL LOAN APPLICATIONS,TOTAL FUNDED AMOUNT, TOTAL RECEIVED AMOUT)*/
SELECT 
	MONTH(issue_date) AS 'MONTH NUMBER',
	DATENAME(MONTH,issue_date) AS 'MONTH' ,
	COUNT(ID) AS 'TOTAL LOAN APPLICATIONS',
	SUM(loan_amount) AS 'TOTAL FUNDED AMOUNT',
	SUM(total_payment) AS 'TOTAL RECEIVED AMOUNT'
FROM BANK_LOAN_DATA
GROUP BY MONTH(issue_date),DATENAME(MONTH,issue_date) 
ORDER BY MONTH(issue_date);

/*REGIONAL ANALYSIS BY STATE (TOTAL LOAN APPLICATIONS,TOTAL FUNDED AMOUNT, TOTAL RECEIVED AMOUT)*/
SELECT 
	address_state,
	COUNT(ID)AS 'TOTAL LOAN APPLICATIONS',
	SUM(loan_amount)AS 'TOTAL FUNDED AMOUNT',
	SUM(total_payment)AS 'TOTAL RECEIVED AMOUNT' 
FROM BANK_LOAN_DATA 
GROUP BY address_state
ORDER BY 'TOTAL LOAN APPLICATIONS'DESC;

/*LOAN TERM ANALYSIS (TOTAL LOAN APPLICATIONS,TOTAL FUNDED AMOUNT, TOTAL RECEIVED AMOUT)*/
SELECT 
	term,
	COUNT(ID)AS 'TOTAL LOAN APPLICATIONS',
	SUM(loan_amount)AS 'TOTAL FUNDED AMOUNT',
	SUM(total_payment)AS 'TOTAL RECEIVED AMOUNT' 
FROM BANK_LOAN_DATA 
GROUP BY term
ORDER BY term;

/*EMPLOYEE LENGTH ANALYSIS (TOTAL LOAN APPLICATIONS,TOTAL FUNDED AMOUNT, TOTAL RECEIVED AMOUT)*/
SELECT 
	emp_length,
	COUNT(ID)AS 'TOTAL LOAN APPLICATIONS',
	SUM(loan_amount)AS 'TOTAL FUNDED AMOUNT',
	SUM(total_payment)AS 'TOTAL RECEIVED AMOUNT' 
FROM BANK_LOAN_DATA 
GROUP BY emp_length
ORDER BY emp_length;

/*LOAN PURPOSE BREAKDOWN (TOTAL LOAN APPLICATIONS,TOTAL FUNDED AMOUNT, TOTAL RECEIVED AMOUT)*/
SELECT 
	purpose,
	COUNT(ID)AS 'TOTAL LOAN APPLICATIONS',
	SUM(loan_amount)AS 'TOTAL FUNDED AMOUNT',
	SUM(total_payment)AS 'TOTAL RECEIVED AMOUNT' 
FROM BANK_LOAN_DATA 
GROUP BY purpose
ORDER BY 'TOTAL LOAN APPLICATIONS' DESC;

/*HOME OWNERSHIP ANALYSIS(TOTAL LOAN APPLICATIONS,TOTAL FUNDED AMOUNT, TOTAL RECEIVED AMOUT)*/
SELECT 
	home_ownership,
	COUNT(ID)AS 'TOTAL LOAN APPLICATIONS',
	SUM(loan_amount)AS 'TOTAL FUNDED AMOUNT',
	SUM(total_payment)AS 'TOTAL RECEIVED AMOUNT' 
FROM BANK_LOAN_DATA 
GROUP BY home_ownership
ORDER BY 'TOTAL LOAN APPLICATIONS' DESC;


SELECT @@SERVERNAME;